export const escudosTimes = {
  'Flamengo Feminino': 'https://logodetimes.com/times/flamengo/logo-flamengo-256.png',
  'Corinthians Feminino': 'https://logodetimes.com/times/corinthians/logo-corinthians-256.png',
  'RB Bragantino Feminino' : 'https://www.futbox.com/img/v1/43c/2d3/5f8/3d4/d46917fcb15759ae7b73_zoom.png',
  'Ferroviária Feminino' : 'https://upload.wikimedia.org/wikipedia/commons/9/95/Escudo_Associa%C3%A7%C3%A3o_Ferrovi%C3%A1ria_de_Esportes.png',
  '3B da Amazônia' : 'https://upload.wikimedia.org/wikipedia/pt/1/1d/3B_da_Amaz%C3%B4nia.png',
  'Real Brasília Feminino' : 'https://upload.wikimedia.org/wikipedia/commons/4/40/RealBras%C3%ADliaFC.png',
  'Sport Recife Feminino' : 'https://sportrecife.com.br/wp-content/uploads/2024/06/image19.png',
  'Juventude Feminino' : 'https://cdn-img.zerozero.pt/img/logos/equipas/2246_imgbank_1683626208.png',
  'América Mineiro Feminino' : 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/Escudo_do_America_Futebol_Clube.svg/1742px-Escudo_do_America_Futebol_Clube.svg.png',
  'Santos Feminino': 'https://logodetimes.com/times/santos/logo-santos-256.png',
  'São Paulo Feminino': 'https://logodetimes.com/times/sao-paulo/logo-sao-paulo-256.png',
  'Palmeiras Feminino': 'https://logodetimes.com/times/palmeiras/logo-palmeiras-256.png',
  'Grêmio Feminino': 'https://logodetimes.com/times/gremio/logo-gremio-256.png',
  'Internacional Feminino': 'https://logodetimes.com/times/internacional/logo-internacional-256.png',
  'Atlético Mineiro Feminino': 'https://logodetimes.com/times/atletico-mineiro/logo-atletico-mineiro-256.png',
  'Cruzeiro Feminino': 'https://logodetimes.com/times/cruzeiro/logo-cruzeiro-256.png',
  'Botafogo Feminino': 'https://logodetimes.com/times/botafogo/logo-botafogo-256.png',
  'Fluminense Feminino': 'https://logodetimes.com/times/fluminense/logo-fluminense-256.png',
  'Vasco Feminino': 'https://s.sde.globo.com/media/organizations/2021/09/04/vasco_SVG.svg',
  'Athletico Paranaense Feminino': 'https://logodetimes.com/times/atletico-paranaense/logo-atletico-paranaense-256.png',
  'Bahia Feminino': 'https://logodetimes.com/times/bahia/logo-bahia-256.png',
  'Fortaleza Feminino': 'https://logodetimes.com/times/fortaleza/logo-fortaleza-256.png',
  'AD Taubaté Feminino' : 'https://upload.wikimedia.org/wikipedia/pt/9/91/Escudo_do_Taubat%C3%A9_Futebol_Feminino.png',
  'Bragantino Feminino' : 'https://www.futbox.com/img/v1/43c/2d3/5f8/3d4/d46917fcb15759ae7b73_zoom.png',
  'Realidade Jovem Feminino' : 'https://www.ogol.com.br/img_icon/logos/equipas/244772_imgbank_1712575877.png',
  'UDA-AL Feminino' : 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR9d7KPkgbjcMJGZboITnqFrYusxD-iMFjtIQ&s',
  'Coritiba Feminino' : 'https://cdn-img.zerozero.pt/img/logos/equipas/2235_imgbank_1683624576.png',  
  'Toledo Feminino' : 'https://www.ogol.com.br/img/logos/equipas/13691_imgbank.png',
  'Brasil de Farroupilha Feminino' : 'https://www.ogol.com.br/img_icon/logos/equipas/11646_imgbank_1688481819.png',
  'Pinda Feminino' : 'https://www.ogol.com.br/img_icon/logos/equipas/262585_imgbank.png',
  'São Raimundo-RR Feminino' : 'https://www.ogol.com.br/img_icon/logos/equipas/3471_imgbank_1683708164.png',
  'Recanto Interativo Feminino' : 'https://www.ogol.com.br/img/logos/equipas/255833_imgbank_1682694222.png',
  'Ceará Feminino' : 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Cear%C3%A1_Sporting_Club_logo.svg/1845px-Cear%C3%A1_Sporting_Club_logo.svg.png',
  'Rolim de Moura-RO Feminino' : 'https://upload.wikimedia.org/wikipedia/pt/4/42/RolimDeMouraEC.png',
  'Doce Mel Feminino' : 'https://upload.wikimedia.org/wikipedia/pt/a/a7/Doce_Mel_Esporte_Clube.png',
  'IAPE-MA Feminino' : 'https://upload.wikimedia.org/wikipedia/pt/7/79/IAPEfc.png',
  'Vila Nova-GO Feminino' : 'https://www.ogol.com.br/img/logos/equipas/3532_imgbank_1683709133.png',
  'Atlético Piauiense Feminino' : 'https://www.ogol.com.br/img/logos/equipas/294975_imgbank_1685012952.png',
  'Manaus FC Feminino' : 'https://www.ogol.com.br/img/logos/equipas/85493_imgbank_1683626236.png',
  'Guarani de Paripueira Feminino' : 'https://www.ogol.com.br/img_icon/logos/equipas/35/291335_logo_20241118193935_guarani_paripueira.png',
  'Ipojuca Feminino' : 'https://www.ogol.com.br/img_icon/logos/equipas/98/72998_logo_ipojuca.png',
  'Atlético de Alagoinhas Feminino' : 'https://www.ogol.com.br/img/logos/equipas/3128_imgbank_1683641721.png',
  'Operário-MT Feminino' : 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiBnztu21un6yXWbI3IJPDMMdDweTG8sP70-5-lMghLCu-OXlyTVLJL11DxcLV5iNw6jAS8H52xvFNcFgAscIfpZDc4prWCfWeWmI5l3uElmLwruQ6KDJt5zrTph-OuDbqtQV-XkiBNvNc/s2048/Oper%25C3%25A1rio+FC+LTDA-MT+%2528BRA%2529+2021+B-03.png',
  'Prosperidade-ES Feminino' : 'https://futebolcapixaba.com/site/wp-content/uploads/2018/09/LOGO-PFC-2023.png',
  'Ypiranga-AP Feminino' : 'https://www.ogol.com.br/img/logos/equipas/3539_imgbank.png',
  'Galvez-AC Feminino' : 'https://s.sde.globo.com/media/organizations/2023/03/20/Galvez-65.png', 
  'Tarumã-AM Feminino' : 'https://s.sde.globo.com/media/organizations/2014/12/13/taruma_65.png',
  'Juventude-SE Feminino' : 'https://s.sde.globo.com/media/organizations/2025/04/11/juv-se.svg',
  'Mixto-PB Feminino' : 'https://s.sde.globo.com/media/teams/2024/11/13/mixto-svg.svg',
  'Operário-MS Feminino' : 'https://s.sde.globo.com/media/organizations/2023/05/01/Operario-MS.svg',
  'Tuna Luso Feminino' : 'https://s.sde.globo.com/media/organizations/2023/05/01/TunaLusoB.svg',
  'CRESSPOM-DF Feminino' : 'https://s.sde.globo.com/media/teams/2016/09/06/Cresspom-df65.png',
  'Itabirito Feminino' : 'https://s.sde.globo.com/media/organizations/2024/01/12/itabirito-66507.svg',
  'Pérolas Negras Feminino' : 'https://s.sde.globo.com/media/organizations/2017/01/04/Perolas-Negras65.png',
  'União-RN Feminino' : 'https://s.sde.globo.com/media/organizations/2022/06/09/Uni%C3%A3o_60x60.png',
  'Paysandu Feminino' : 'https://s.sde.globo.com/media/organizations/2019/05/29/Paysandu.svg',
  'São José-SP Feminino' : 'https://s.sde.globo.com/media/organizations/2019/03/23/sao_jose_ec-sp-01.svg',
  'Criciúma Feminino' : 'https://s.sde.globo.com/media/organizations/2024/03/28/Criciuma-2024.svg',
  'Atlético-MG Feminino' : 'https://s.sde.globo.com/media/organizations/2018/03/10/atletico-mg.svg',
  'Minas Brasília Feminino' : 'https://s.sde.globo.com/media/organizations/2019/03/03/minas.svg',
  'Ação-MT Feminino' : 'https://s.sde.globo.com/media/organizations/2017/12/07/acao-65.png',
  'Taubaté Feminino' : 'https://s.sde.globo.com/media/organizations/2024/01/12/taubate-66511.svg',
  'Avaí/Kindermann Feminino' : 'https://s.sde.globo.com/media/organizations/2020/02/06/Ava%C3%AD_Kindermann.svg',
  'Rio Negro-RR Feminino' : 'https://s.sde.globo.com/media/organizations/2023/05/05/Rio_Negro-RR.svg',
  'Mixto-MT Feminino' : 'https://s.sde.globo.com/media/organizations/2025/08/03/mixto.svg',
  'Remo Feminino' : 'https://s.sde.globo.com/media/organizations/2021/02/25/Remo-PA.svg',
  'Itacoatiara Feminino' : 'https://s.sde.globo.com/media/organizations/2025/04/16/escudop-itacoatiara_2_hfbcSEf.png',
  'Vitória Feminino' : 'https://s.sde.globo.com/media/organizations/2024/04/09/escudo-vitoria-svg-69281.svg',
  'Juventude-RS Feminino' : 'https://s.sde.globo.com/media/organizations/2021/04/29/Juventude-2021-01.svg',
  'Sport Feminino' : 'https://s.sde.globo.com/media/organizations/2018/03/11/sport.svg',
  '3B da Amazônia Feminino' : 'https://s.sde.globo.com/media/organizations/2025/05/13/3B_da_Amaz%C3%B4nia.svg',
  'América-MG Feminino' : 'https://s.sde.globo.com/media/organizations/2024/05/07/America-MG-branco.svg',


  'Manchester City WFC' : 'https://upload.wikimedia.org/wikipedia/en/thumb/e/eb/Manchester_City_FC_badge.svg/1200px-Manchester_City_FC_badge.svg.png',
  'Liverpool FC Feminino' : 'https://www.ogol.com.br/img/logos/equipas/85_imgbank_1724929992.png',
  'Manchester United WFC': 'https://upload.wikimedia.org/wikipedia/pt/b/b6/Manchester_United_FC_logo.png',
  'Crystal Palace FC Feminino' : 'https://www.ogol.com.br/img/logos/equipas/2597_imgbank_1683908036.png',
  'Leicester City WFC' : 'https://upload.wikimedia.org/wikipedia/en/thumb/2/2d/Leicester_City_crest.svg/1200px-Leicester_City_crest.svg.png',
  'Tottenham Feminino' : 'https://cdn-icons-png.flaticon.com/512/824/824738.png',
  'West Ham Feminino' : 'https://www.ogol.com.br/img/logos/equipas/94_imgbank_1683907588.png',
  'Everton FC Feminino' : 'https://upload.wikimedia.org/wikipedia/pt/a/ae/Everton_FC_logo_2014.png',
  'London City Lionesses' : 'https://upload.wikimedia.org/wikipedia/en/1/14/LCL_Crest.png',
  'Chelsea Feminino': 'https://logodownload.org/wp-content/uploads/2017/02/chelsea-fc-logo-1.png',
  'Aston Villa WFC' : 'https://upload.wikimedia.org/wikipedia/en/9/9a/Aston_Villa_FC_new_crest.svg',
  'Brighton WFC' : 'https://upload.wikimedia.org/wikipedia/en/thumb/f/fd/Brighton_%26_Hove_Albion_logo.svg/1200px-Brighton_%26_Hove_Albion_logo.svg.png',
  'Arsenal WFC' : 'https://upload.wikimedia.org/wikipedia/en/5/53/Arsenal_FC.svg',
  'Barcelona Feminino': 'https://logodownload.org/wp-content/uploads/2018/07/fc-barcelona-logo-1.png',
  'Real Madrid Feminino': 'https://logodownload.org/wp-content/uploads/2018/07/real-madrid-logo-1.png',

  'Australia Feminino' : 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Australia_national_football_team_badge.svg/250px-Australia_national_football_team_badge.svg.png',
  'Slovenia Feminino' : 'https://upload.wikimedia.org/wikipedia/pt/b/b9/Slovenia_national_team_logo.png',
  'Nigeria Feminino' : 'https://upload.wikimedia.org/wikipedia/pt/b/be/NigeriaFA.png',
  'Ghana Feminino' : 'https://upload.wikimedia.org/wikipedia/pt/thumb/6/67/Ghana_Football_Association.png/250px-Ghana_Football_Association.png',
  'Inglaterra Feminino' : 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Arms_of_The_Football_Association.svg/250px-Arms_of_The_Football_Association.svg.png',
  'Jamaica Feminino' : 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Jamaica_FA.svg/1200px-Jamaica_FA.svg.png',
  'EUA Feminino' : 'https://upload.wikimedia.org/wikipedia/commons/4/4f/United_States_women%27s_national_soccer_team_logo.svg',
  'Irlanda Feminino' : 'https://upload.wikimedia.org/wikipedia/pt/d/df/FAIreland.png',
  'Bielorrússia Feminino' : 'https://www.ogol.com.br/img/bandeiras/190_blr_imgbank_flag.png',
  'Azerbaijão Feminino' : 'https://blogger.googleusercontent.com/img/a/AVvXsEhpas6m3IofyNk1KUPIHiUV9_pS6yxlYRDpJFPWORwQf2BPtNtPxmNCFUb26YIJSkBxvpwVIVrrDQmcLsubZ8ewafgX9i8TJASbC-j4pCBpLMHxikC_7YhjCcRQsphGEYgm6sJ-ehf2hA5pfBuHZ3ZOJunHWXkrj4hoI3UvFe5qOK2dOluF2MaAyxMYWIw',
  'Estónia Feminino' : 'https://upload.wikimedia.org/wikipedia/pt/8/80/EestiJL.png',
  'Kosovo Feminino' : 'https://upload.wikimedia.org/wikipedia/pt/2/2f/FFKosov%C3%ABs.png',
  'Sévia Feminino' : 'https://upload.wikimedia.org/wikipedia/pt/f/f6/FSSrbije.png',
  'Russia Feminino' : 'https://upload.wikimedia.org/wikipedia/pt/7/77/Russian_Football_Union.png',
  'Canada Feminino' : 'https://upload.wikimedia.org/wikipedia/pt/7/7a/Logotipo_Sele%C3%A7%C3%A3o_Canad%C3%A1.png',
  'Mexico Feminino' : 'https://upload.wikimedia.org/wikipedia/pt/f/f3/Mexico_national_football_team_crest_%282022%29.png',
  'Colombia Feminino' : 'https://images.seeklogo.com/logo-png/24/2/colombian-soccer-federation-logo-png_seeklogo-248047.png',
  'Chile Feminino' : 'https://upload.wikimedia.org/wikipedia/commons/6/6a/Logo_Federaci%C3%B3n_de_F%C3%BAtbol_de_Chile.png',
  'Bolivia Feminino' : 'https://upload.wikimedia.org/wikipedia/pt/9/9e/Federaci%C3%B3n_Boliviana_de_F%C3%BAtbol.png',
  'Panama Feminino' : 'https://upload.wikimedia.org/wikipedia/pt/a/aa/Panama_FA_2.svg.png',
};

export const getEscudoTime = (nomeTime) => {
  return escudosTimes[nomeTime] || null;
};