// src/utils/escudos.js
export const escudosTimes = {
  'Flamengo Feminino': 'https://logodetimes.com/times/flamengo/logo-flamengo-256.png',
  'Corinthians Feminino': 'https://logodetimes.com/times/corinthians/logo-corinthians-256.png',
  'RB Bragantino Feminino' : 'https://www.futbox.com/img/v1/43c/2d3/5f8/3d4/d46917fcb15759ae7b73_zoom.png',
  'Ferroviária Feminino' : 'https://upload.wikimedia.org/wikipedia/commons/9/95/Escudo_Associa%C3%A7%C3%A3o_Ferrovi%C3%A1ria_de_Esportes.png',
  '3B da Amazônia' : 'https://upload.wikimedia.org/wikipedia/pt/1/1d/3B_da_Amaz%C3%B4nia.png',
  'Real Brasília Feminino' : 'https://upload.wikimedia.org/wikipedia/commons/4/40/RealBras%C3%ADliaFC.png',
  'Sport Recife Feminino' : 'https://sportrecife.com.br/wp-content/uploads/2024/06/image19.png',
  'Juventude Feminino' : 'https://cdn-img.zerozero.pt/img/logos/equipas/2246_imgbank_1683626208.png',
  'América Mineiro Feminino' : 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/Escudo_do_America_Futebol_Clube.svg/1742px-Escudo_do_America_Futebol_Clube.svg.png',
  'Santos Feminino': 'https://logodetimes.com/times/santos/logo-santos-256.png',
  'São Paulo Feminino': 'https://logodetimes.com/times/sao-paulo/logo-sao-paulo-256.png',
  'Palmeiras Feminino': 'https://logodetimes.com/times/palmeiras/logo-palmeiras-256.png',
  'Grêmio Feminino': 'https://logodetimes.com/times/gremio/logo-gremio-256.png',
  'Internacional Feminino': 'https://logodetimes.com/times/internacional/logo-internacional-256.png',
  'Atlético Mineiro Feminino': 'https://logodetimes.com/times/atletico-mineiro/logo-atletico-mineiro-256.png',
  'Cruzeiro Feminino': 'https://logodetimes.com/times/cruzeiro/logo-cruzeiro-256.png',
  'Botafogo Feminino': 'https://logodetimes.com/times/botafogo/logo-botafogo-256.png',
  'Fluminense Feminino': 'https://logodetimes.com/times/fluminense/logo-fluminense-256.png',
  'Vasco Feminino': 'https://logodetimes.com/times/vasco/logo-vasco-256.png',
  'Athletico Paranaense Feminino': 'https://logodetimes.com/times/atletico-paranaense/logo-atletico-paranaense-256.png',
  'Bahia Feminino': 'https://logodetimes.com/times/bahia/logo-bahia-256.png',
  'Fortaleza Feminino': 'https://logodetimes.com/times/fortaleza/logo-fortaleza-256.png',

  'Manchester City WFC' : 'https://upload.wikimedia.org/wikipedia/en/thumb/e/eb/Manchester_City_FC_badge.svg/1200px-Manchester_City_FC_badge.svg.png',
  'Liverpool FC Feminino' : 'https://www.ogol.com.br/img/logos/equipas/85_imgbank_1724929992.png',
  'Manchester United WFC': 'https://upload.wikimedia.org/wikipedia/pt/b/b6/Manchester_United_FC_logo.png',
  'Crystal Palace FC Feminino' : 'https://www.ogol.com.br/img/logos/equipas/2597_imgbank_1683908036.png',
  'Leicester City WFC' : 'https://upload.wikimedia.org/wikipedia/en/thumb/2/2d/Leicester_City_crest.svg/1200px-Leicester_City_crest.svg.png',
  'Tottenham Feminino' : 'https://cdn-icons-png.flaticon.com/512/824/824738.png',
  'West Ham Feminino' : 'https://www.ogol.com.br/img/logos/equipas/94_imgbank_1683907588.png',
  'Everton FC Feminino' : 'https://upload.wikimedia.org/wikipedia/pt/a/ae/Everton_FC_logo_2014.png',
  'London City Lionesses' : 'https://upload.wikimedia.org/wikipedia/en/1/14/LCL_Crest.png',
  'Chelsea Feminino': 'https://logodownload.org/wp-content/uploads/2017/02/chelsea-fc-logo-1.png',
  'Aston Villa WFC' : 'https://upload.wikimedia.org/wikipedia/en/9/9a/Aston_Villa_FC_new_crest.svg',
  'Brighton WFC' : 'https://upload.wikimedia.org/wikipedia/en/thumb/f/fd/Brighton_%26_Hove_Albion_logo.svg/1200px-Brighton_%26_Hove_Albion_logo.svg.png',
  'Arsenal WFC' : 'https://upload.wikimedia.org/wikipedia/en/5/53/Arsenal_FC.svg',
  'Barcelona Feminino': 'https://logodownload.org/wp-content/uploads/2018/07/fc-barcelona-logo-1.png',
  'Real Madrid Feminino': 'https://logodownload.org/wp-content/uploads/2018/07/real-madrid-logo-1.png',

  'Australia Feminino' : 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Australia_national_football_team_badge.svg/250px-Australia_national_football_team_badge.svg.png',
  'Slovenia Feminino' : 'https://upload.wikimedia.org/wikipedia/pt/b/b9/Slovenia_national_team_logo.png',
  'Nigeria Feminino' : 'https://upload.wikimedia.org/wikipedia/pt/b/be/NigeriaFA.png',
  'Ghana Feminino' : 'https://upload.wikimedia.org/wikipedia/pt/thumb/6/67/Ghana_Football_Association.png/250px-Ghana_Football_Association.png',
  'Inglaterra Feminino' : 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Arms_of_The_Football_Association.svg/250px-Arms_of_The_Football_Association.svg.png',
  'Jamaica Feminino' : 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Jamaica_FA.svg/1200px-Jamaica_FA.svg.png',
  'EUA Feminino' : 'https://upload.wikimedia.org/wikipedia/commons/4/4f/United_States_women%27s_national_soccer_team_logo.svg',
  'Irlanda Feminino' : 'https://upload.wikimedia.org/wikipedia/pt/d/df/FAIreland.png',
  'Bielorrússia Feminino' : 'https://www.ogol.com.br/img/bandeiras/190_blr_imgbank_flag.png',
  'Azerbaijão Feminino' : 'https://blogger.googleusercontent.com/img/a/AVvXsEhpas6m3IofyNk1KUPIHiUV9_pS6yxlYRDpJFPWORwQf2BPtNtPxmNCFUb26YIJSkBxvpwVIVrrDQmcLsubZ8ewafgX9i8TJASbC-j4pCBpLMHxikC_7YhjCcRQsphGEYgm6sJ-ehf2hA5pfBuHZ3ZOJunHWXkrj4hoI3UvFe5qOK2dOluF2MaAyxMYWIw',
  'Estónia Feminino' : 'https://upload.wikimedia.org/wikipedia/pt/8/80/EestiJL.png',
  'Kosovo Feminino' : 'https://upload.wikimedia.org/wikipedia/pt/2/2f/FFKosov%C3%ABs.png',
  'Sévia Feminino' : 'https://upload.wikimedia.org/wikipedia/pt/f/f6/FSSrbije.png',
  'Russia Feminino' : 'https://upload.wikimedia.org/wikipedia/pt/7/77/Russian_Football_Union.png',
  'Canada Feminino' : 'https://upload.wikimedia.org/wikipedia/pt/7/7a/Logotipo_Sele%C3%A7%C3%A3o_Canad%C3%A1.png',
  'Mexico Feminino' : 'https://upload.wikimedia.org/wikipedia/pt/f/f3/Mexico_national_football_team_crest_%282022%29.png',
  'Colombia Feminino' : 'https://images.seeklogo.com/logo-png/24/2/colombian-soccer-federation-logo-png_seeklogo-248047.png',
  'Chile Feminino' : 'https://upload.wikimedia.org/wikipedia/commons/6/6a/Logo_Federaci%C3%B3n_de_F%C3%BAtbol_de_Chile.png',
  'Bolivia Feminino' : 'https://upload.wikimedia.org/wikipedia/pt/9/9e/Federaci%C3%B3n_Boliviana_de_F%C3%BAtbol.png',
  'Panama Feminino' : 'https://upload.wikimedia.org/wikipedia/pt/a/aa/Panama_FA_2.svg.png',


};

export const getEscudoTime = (nomeTime) => {
  return escudosTimes[nomeTime] || null;
};